### ISSUE TITLE
dont remove color of text on setting?

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_MatrixPortal#43] opened 2020-11-09 15:32 UTC
https://forums.adafruit.com/viewtopic.php?f=60&t=171593&p=837802#p837802

**Comment by FoamyGuy** [comment] 2020-11-09 17:36
I took a peek into this. The root cause is the `set_text_color()` ignores the incoming color if label for that index doesn't exist yet. https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/blob/f32f3ca8785bf524ceacdbeed8fcb993240c5e6f/adafruit_matrixportal/matrixportal.py#L257

Since the set color doesn't get kept it can't be set on the label once it gets created. 

One option is to allow setting the color before the text has been set. I can try to fix this today.

**Comment by makermelissa** [comment] 2020-11-10 22:39
Fixed via #44

**Closed as completed by makermelissa** 2020-11-10 22:39 UTC
